### ISSUE TITLE
head is not defined when use markdown plugins

### ISSUE THREAD

**Issue by yangzhiyao** [jchull/reveal.js-webpack-starter#1]
when i use markdown plugins
uncomment the js file:
dependencies: [{...

chrome say "Uncaught ReferenceError: head is not defined"
and i try to add to my main.js:
var head = require("headjs");

it's return:
Error: Cannot find module 'headjs'

how can i make the headjs to package js file or i must directly use it from my html?

**Comment by jchull** [comment]
I don't know the particulars of your project or that lib, but if you require() any libs in the index.js, they should be packaged up, the console output will tell you what is built. If you have any other JS files, they need to also be require()'ed
Also make sure you have installed the third party dep and it is in node_modules
