### ISSUE TITLE
Enable plugins

### ISSUE THREAD

**Issue by rparree** [jchull/reveal.js-webpack-starter#2]
Hi,

I am not using your webpack starter, but have been doing the same. I am running into trouble with the plugins. How can we enable plugins (especially the `zoom` plugin as it refers to the Reveal object.

Have you've been able to get the plugins working with webpack?

tx.,

**Comment by rparree** [comment]
Was able to use the following (might be helpful for you as well)

```js
import * as $ from "jquery";
import Reveal from "reveal.js/js/reveal"
import "reveal.js/lib/js/head.min"

$(function () {
    Reveal.initialize({
        controls: true,
        progress: true,
        history: true,
        center: true,
        slideNumber: true,
        margin: 0.0,
        transition: 'slide',
        // based on 1280x800
        width: 1216,
        height: 736,

        // Optional libraries used to extend on reveal.js
        dependencies: []
    });
    // plugins
    require( "imports-loader?Reveal=reveal.js/js/reveal!reveal.js/plugin/notes/notes")
    require( "imports-loader?Reveal=reveal.js/js/reveal!reveal.js/plugin/zoom-js/zoom")
    require( "imports-loader?Reveal=reveal.js/js/reveal!reveal.js/plugin/markdown/marked")
    require( "imports-loader?Reveal=reveal.js/js/reveal!reveal.js/plugin/markdown/markdown")
})

```

**Comment by vorlando** [comment]
Thanks, your code example helped solve a similar problem!!

**Comment by Art4** [comment]
Thanks @rparree :+1:

**Comment by jchull** [comment]
Thanks @rparree 
Just getting around to updating a few things, I will check out plugins

**Comment by jchull** [comment]
I added Reveal to the webpack provide plugin so it is visible to the plugins. Seems like the code highlight plugin currently has a minification issue, so I used highlight.js directly.
