### ISSUE TITLE
adding htmlwebpackplugin

### ISSUE THREAD

**Issue by blachawk** [jchull/reveal.js-webpack-starter#4]
Would it be possible to associate the htmlwebpackplugin to this project?  if so, are their modifications we need to consider?

**Comment by jchull** [comment]
Do you have more info about what you are trying to do? It looks like I have some more-recent changes in a local branch that I need to look at and see if they should be pushed, I will take a look tonight. It does not appear to work in master, but it was working where running 'npm run build' would result in the contents of the dist directory being such that you could share it as a zip and run it on any browser, but right now it appears the css is not included.

**Comment by blachawk** [comment]
my immediate goal is to find out how if this package can deploy multiple reveal.js projects in the /dist directory as separate files, or as separate sub directories. If your package already does that, my bad.  I didn't get that far in discovering this yet...

**Comment by jchull** [comment]
I fixed a few broken things today, so you should definitely update if you like your presentation to function. It does not build separate distributions for you, I usually just clone from a branch that has my branding already added and build from there. To have multiple presentations, that probably means multiple entry points for webpack, just adding more HTML files currently won't work.

**Comment by blachawk** [comment]
Thanks for the quick feedback!  I totally forgot about "branch cloning" to make the concept of various projects.  That is definitely one approach to take.
